// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	Aggregation
	Request
	Response
*/
package entry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Aggregation struct {
	Request   *Request  `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response  *Response `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	ErrorCode string    `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *Aggregation) Reset()                    { *m = Aggregation{} }
func (m *Aggregation) String() string            { return proto.CompactTextString(m) }
func (*Aggregation) ProtoMessage()               {}
func (*Aggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Aggregation) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Aggregation) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Aggregation) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type Request struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Uid  string `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	Ip   string `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Request) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Response struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Status  string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Aggregation)(nil), "Aggregation")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// 获取用户状态ls
	GetStatus(ctx context.Context, in *Aggregation, opts ...grpc.CallOption) (*Aggregation, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetStatus(ctx context.Context, in *Aggregation, opts ...grpc.CallOption) (*Aggregation, error) {
	out := new(Aggregation)
	err := grpc.Invoke(ctx, "/Greeter/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// 获取用户状态ls
	GetStatus(context.Context, *Aggregation) (*Aggregation, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Aggregation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetStatus(ctx, req.(*Aggregation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Greeter_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x5a, 0x9a, 0xec, 0x54, 0xa4, 0xcc, 0x41, 0x16, 0x41, 0x28, 0x0b, 0x42, 0xbd,
	0xe4, 0x50, 0x7d, 0x01, 0xf1, 0xd0, 0x8b, 0x20, 0xac, 0x0f, 0x20, 0xd1, 0x1d, 0x62, 0x20, 0xcd,
	0xc4, 0xd9, 0x0d, 0x7d, 0x7d, 0x71, 0xb3, 0x11, 0xc5, 0xdb, 0x7c, 0xff, 0xec, 0x7c, 0x3b, 0x0c,
	0x6c, 0x3e, 0xa8, 0xeb, 0xf8, 0xc4, 0xd2, 0xb9, 0x6a, 0x10, 0x0e, 0x6c, 0x4e, 0xb0, 0x7e, 0x68,
	0x1a, 0xa1, 0xa6, 0x0e, 0x2d, 0xf7, 0x68, 0xa0, 0x10, 0xfa, 0x1c, 0xc9, 0x07, 0x9d, 0x6d, 0xb3,
	0xdd, 0x7a, 0x5f, 0x56, 0x76, 0x62, 0x3b, 0x37, 0xf0, 0x06, 0x4a, 0x21, 0x3f, 0x70, 0xef, 0x49,
	0xe7, 0xf1, 0x91, 0xaa, 0x6c, 0x0a, 0xec, 0x4f, 0x0b, 0xaf, 0x01, 0x48, 0x84, 0xe5, 0xf5, 0x9d,
	0x1d, 0xe9, 0xc5, 0x36, 0xdb, 0x29, 0xab, 0x62, 0xf2, 0xc8, 0x8e, 0xcc, 0x33, 0x14, 0xc9, 0x8c,
	0x17, 0x90, 0xb7, 0x2e, 0xfe, 0xa7, 0x6c, 0xde, 0x3a, 0x44, 0x58, 0xf6, 0xf5, 0x71, 0x92, 0x2b,
	0x1b, 0x6b, 0xdc, 0xc0, 0x62, 0x6c, 0x5d, 0xd2, 0x7c, 0x97, 0x71, 0x6a, 0xd0, 0xcb, 0x34, 0x35,
	0x98, 0x27, 0x28, 0xe7, 0x2d, 0xfe, 0x19, 0x35, 0x14, 0x47, 0xf2, 0xbe, 0x6e, 0x66, 0xe9, 0x8c,
	0x78, 0x09, 0x2b, 0x1f, 0xea, 0x30, 0xfa, 0xa4, 0x4e, 0xb4, 0xbf, 0x87, 0xe2, 0x20, 0x44, 0x81,
	0x04, 0x6f, 0x41, 0x1d, 0x28, 0xbc, 0xc4, 0x1c, 0xcf, 0xab, 0x5f, 0xe7, 0xba, 0xfa, 0x43, 0xe6,
	0xec, 0x6d, 0x15, 0x8f, 0x7a, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x23, 0xc0, 0xa8, 0x68,
	0x01, 0x00, 0x00,
}
