// Code generated by protoc-gen-go.
// source: baidu_mobads_api_5.proto
// DO NOT EDIT!

/*
Package mobads_apiv5 is a generated protocol buffer package.

It is generated from these files:
	baidu_mobads_api_5.proto

It has these top-level messages:
	Version
	App
	UdId
	Size
	Device
	WiFiAp
	Network
	Gps
	Tracking
	Video
	AdSlot
	MobadsRequest
	MetaIndex
	MaterialMeta
	Ad
	MobadsResponse
*/
package baidu

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 设备类型
type Device_DeviceType int32

const (
	Device_PHONE  Device_DeviceType = 1
	Device_TABLET Device_DeviceType = 2
)

var Device_DeviceType_name = map[int32]string{
	1: "PHONE",
	2: "TABLET",
}
var Device_DeviceType_value = map[string]int32{
	"PHONE":  1,
	"TABLET": 2,
}

func (x Device_DeviceType) Enum() *Device_DeviceType {
	p := new(Device_DeviceType)
	*p = x
	return p
}
func (x Device_DeviceType) String() string {
	return proto.EnumName(Device_DeviceType_name, int32(x))
}
func (x *Device_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_DeviceType_value, data, "Device_DeviceType")
	if err != nil {
		return err
	}
	*x = Device_DeviceType(value)
	return nil
}
func (Device_DeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

// 操作系统类型
type Device_OsType int32

const (
	Device_ANDROID Device_OsType = 1
	Device_IOS     Device_OsType = 2
)

var Device_OsType_name = map[int32]string{
	1: "ANDROID",
	2: "IOS",
}
var Device_OsType_value = map[string]int32{
	"ANDROID": 1,
	"IOS":     2,
}

func (x Device_OsType) Enum() *Device_OsType {
	p := new(Device_OsType)
	*p = x
	return p
}
func (x Device_OsType) String() string {
	return proto.EnumName(Device_OsType_name, int32(x))
}
func (x *Device_OsType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_OsType_value, data, "Device_OsType")
	if err != nil {
		return err
	}
	*x = Device_OsType(value)
	return nil
}
func (Device_OsType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

// 网络连接类型
type Network_ConnectionType int32

const (
	Network_CONNECTION_UNKNOWN Network_ConnectionType = 0
	Network_CELL_UNKNOWN       Network_ConnectionType = 1
	Network_CELL_2G            Network_ConnectionType = 2
	Network_CELL_3G            Network_ConnectionType = 3
	Network_CELL_4G            Network_ConnectionType = 4
	Network_CELL_5G            Network_ConnectionType = 5
	Network_WIFI               Network_ConnectionType = 100
	Network_ETHERNET           Network_ConnectionType = 101
	Network_NEW_TYPE           Network_ConnectionType = 999
)

var Network_ConnectionType_name = map[int32]string{
	0:   "CONNECTION_UNKNOWN",
	1:   "CELL_UNKNOWN",
	2:   "CELL_2G",
	3:   "CELL_3G",
	4:   "CELL_4G",
	5:   "CELL_5G",
	100: "WIFI",
	101: "ETHERNET",
	999: "NEW_TYPE",
}
var Network_ConnectionType_value = map[string]int32{
	"CONNECTION_UNKNOWN": 0,
	"CELL_UNKNOWN":       1,
	"CELL_2G":            2,
	"CELL_3G":            3,
	"CELL_4G":            4,
	"CELL_5G":            5,
	"WIFI":               100,
	"ETHERNET":           101,
	"NEW_TYPE":           999,
}

func (x Network_ConnectionType) Enum() *Network_ConnectionType {
	p := new(Network_ConnectionType)
	*p = x
	return p
}
func (x Network_ConnectionType) String() string {
	return proto.EnumName(Network_ConnectionType_name, int32(x))
}
func (x *Network_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_ConnectionType_value, data, "Network_ConnectionType")
	if err != nil {
		return err
	}
	*x = Network_ConnectionType(value)
	return nil
}
func (Network_ConnectionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

// 移动运营商类型
type Network_OperatorType int32

const (
	Network_UNKNOWN_OPERATOR Network_OperatorType = 0
	Network_CHINA_MOBILE     Network_OperatorType = 1
	Network_CHINA_TELECOM    Network_OperatorType = 2
	Network_CHINA_UNICOM     Network_OperatorType = 3
	Network_OTHER_OPERATOR   Network_OperatorType = 99
)

var Network_OperatorType_name = map[int32]string{
	0:  "UNKNOWN_OPERATOR",
	1:  "CHINA_MOBILE",
	2:  "CHINA_TELECOM",
	3:  "CHINA_UNICOM",
	99: "OTHER_OPERATOR",
}
var Network_OperatorType_value = map[string]int32{
	"UNKNOWN_OPERATOR": 0,
	"CHINA_MOBILE":     1,
	"CHINA_TELECOM":    2,
	"CHINA_UNICOM":     3,
	"OTHER_OPERATOR":   99,
}

func (x Network_OperatorType) Enum() *Network_OperatorType {
	p := new(Network_OperatorType)
	*p = x
	return p
}
func (x Network_OperatorType) String() string {
	return proto.EnumName(Network_OperatorType_name, int32(x))
}
func (x *Network_OperatorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_OperatorType_value, data, "Network_OperatorType")
	if err != nil {
		return err
	}
	*x = Network_OperatorType(value)
	return nil
}
func (Network_OperatorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

// GPS坐标类型
type Gps_CoordinateType int32

const (
	Gps_WGS84 Gps_CoordinateType = 1
	Gps_GCJ02 Gps_CoordinateType = 2
	Gps_BD09  Gps_CoordinateType = 3
)

var Gps_CoordinateType_name = map[int32]string{
	1: "WGS84",
	2: "GCJ02",
	3: "BD09",
}
var Gps_CoordinateType_value = map[string]int32{
	"WGS84": 1,
	"GCJ02": 2,
	"BD09":  3,
}

func (x Gps_CoordinateType) Enum() *Gps_CoordinateType {
	p := new(Gps_CoordinateType)
	*p = x
	return p
}
func (x Gps_CoordinateType) String() string {
	return proto.EnumName(Gps_CoordinateType_name, int32(x))
}
func (x *Gps_CoordinateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gps_CoordinateType_value, data, "Gps_CoordinateType")
	if err != nil {
		return err
	}
	*x = Gps_CoordinateType(value)
	return nil
}
func (Gps_CoordinateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

// 广告展示过程事件类型
type Tracking_TrackingEvent int32

const (
	// 广告展示过程共性事件
	Tracking_AD_CLICK    Tracking_TrackingEvent = 0
	Tracking_AD_EXPOSURE Tracking_TrackingEvent = 1
	Tracking_AD_CLOSE    Tracking_TrackingEvent = 2
	// 视频类广告展示过程事件
	Tracking_VIDEO_AD_START            Tracking_TrackingEvent = 101000
	Tracking_VIDEO_AD_FULL_SCREEN      Tracking_TrackingEvent = 101001
	Tracking_VIDEO_AD_END              Tracking_TrackingEvent = 101002
	Tracking_VIDEO_AD_START_CARD_CLICK Tracking_TrackingEvent = 101003
	// 下载类广告推广APP相关事件
	Tracking_APP_AD_DOWNLOAD Tracking_TrackingEvent = 102000
	Tracking_APP_AD_INSTALL  Tracking_TrackingEvent = 102001
	Tracking_APP_AD_ACTIVE   Tracking_TrackingEvent = 102002
)

var Tracking_TrackingEvent_name = map[int32]string{
	0:      "AD_CLICK",
	1:      "AD_EXPOSURE",
	2:      "AD_CLOSE",
	101000: "VIDEO_AD_START",
	101001: "VIDEO_AD_FULL_SCREEN",
	101002: "VIDEO_AD_END",
	101003: "VIDEO_AD_START_CARD_CLICK",
	102000: "APP_AD_DOWNLOAD",
	102001: "APP_AD_INSTALL",
	102002: "APP_AD_ACTIVE",
}
var Tracking_TrackingEvent_value = map[string]int32{
	"AD_CLICK":                  0,
	"AD_EXPOSURE":               1,
	"AD_CLOSE":                  2,
	"VIDEO_AD_START":            101000,
	"VIDEO_AD_FULL_SCREEN":      101001,
	"VIDEO_AD_END":              101002,
	"VIDEO_AD_START_CARD_CLICK": 101003,
	"APP_AD_DOWNLOAD":           102000,
	"APP_AD_INSTALL":            102001,
	"APP_AD_ACTIVE":             102002,
}

func (x Tracking_TrackingEvent) Enum() *Tracking_TrackingEvent {
	p := new(Tracking_TrackingEvent)
	*p = x
	return p
}
func (x Tracking_TrackingEvent) String() string {
	return proto.EnumName(Tracking_TrackingEvent_name, int32(x))
}
func (x *Tracking_TrackingEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Tracking_TrackingEvent_value, data, "Tracking_TrackingEvent")
	if err != nil {
		return err
	}
	*x = Tracking_TrackingEvent(value)
	return nil
}
func (Tracking_TrackingEvent) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type Video_CopyRight int32

const (
	Video_CR_NONE  Video_CopyRight = 0
	Video_CR_EXIST Video_CopyRight = 1
	Video_CR_UGC   Video_CopyRight = 2
	Video_CR_OTHER Video_CopyRight = 3
)

var Video_CopyRight_name = map[int32]string{
	0: "CR_NONE",
	1: "CR_EXIST",
	2: "CR_UGC",
	3: "CR_OTHER",
}
var Video_CopyRight_value = map[string]int32{
	"CR_NONE":  0,
	"CR_EXIST": 1,
	"CR_UGC":   2,
	"CR_OTHER": 3,
}

func (x Video_CopyRight) Enum() *Video_CopyRight {
	p := new(Video_CopyRight)
	*p = x
	return p
}
func (x Video_CopyRight) String() string {
	return proto.EnumName(Video_CopyRight_name, int32(x))
}
func (x *Video_CopyRight) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Video_CopyRight_value, data, "Video_CopyRight")
	if err != nil {
		return err
	}
	*x = Video_CopyRight(value)
	return nil
}
func (Video_CopyRight) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

// 请求协议类型
type MobadsRequest_RequestProtocolType int32

const (
	MobadsRequest_UNKNOWN_PROTOCOL_TYPE MobadsRequest_RequestProtocolType = 0
	MobadsRequest_HTTP_PROTOCOL_TYPE    MobadsRequest_RequestProtocolType = 1
	MobadsRequest_HTTPS_PROTOCOL_TYPE   MobadsRequest_RequestProtocolType = 2
)

var MobadsRequest_RequestProtocolType_name = map[int32]string{
	0: "UNKNOWN_PROTOCOL_TYPE",
	1: "HTTP_PROTOCOL_TYPE",
	2: "HTTPS_PROTOCOL_TYPE",
}
var MobadsRequest_RequestProtocolType_value = map[string]int32{
	"UNKNOWN_PROTOCOL_TYPE": 0,
	"HTTP_PROTOCOL_TYPE":    1,
	"HTTPS_PROTOCOL_TYPE":   2,
}

func (x MobadsRequest_RequestProtocolType) Enum() *MobadsRequest_RequestProtocolType {
	p := new(MobadsRequest_RequestProtocolType)
	*p = x
	return p
}
func (x MobadsRequest_RequestProtocolType) String() string {
	return proto.EnumName(MobadsRequest_RequestProtocolType_name, int32(x))
}
func (x *MobadsRequest_RequestProtocolType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MobadsRequest_RequestProtocolType_value, data, "MobadsRequest_RequestProtocolType")
	if err != nil {
		return err
	}
	*x = MobadsRequest_RequestProtocolType(value)
	return nil
}
func (MobadsRequest_RequestProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

// 创意类型
type MaterialMeta_CreativeType int32

const (
	MaterialMeta_NO_TYPE   MaterialMeta_CreativeType = 0
	MaterialMeta_TEXT      MaterialMeta_CreativeType = 1
	MaterialMeta_IMAGE     MaterialMeta_CreativeType = 2
	MaterialMeta_TEXT_ICON MaterialMeta_CreativeType = 3
	MaterialMeta_VIDEO     MaterialMeta_CreativeType = 4
)

var MaterialMeta_CreativeType_name = map[int32]string{
	0: "NO_TYPE",
	1: "TEXT",
	2: "IMAGE",
	3: "TEXT_ICON",
	4: "VIDEO",
}
var MaterialMeta_CreativeType_value = map[string]int32{
	"NO_TYPE":   0,
	"TEXT":      1,
	"IMAGE":     2,
	"TEXT_ICON": 3,
	"VIDEO":     4,
}

func (x MaterialMeta_CreativeType) Enum() *MaterialMeta_CreativeType {
	p := new(MaterialMeta_CreativeType)
	*p = x
	return p
}
func (x MaterialMeta_CreativeType) String() string {
	return proto.EnumName(MaterialMeta_CreativeType_name, int32(x))
}
func (x *MaterialMeta_CreativeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_CreativeType_value, data, "MaterialMeta_CreativeType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_CreativeType(value)
	return nil
}
func (MaterialMeta_CreativeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

// 交互类型
type MaterialMeta_InteractionType int32

const (
	MaterialMeta_NO_INTERACTION MaterialMeta_InteractionType = 0
	MaterialMeta_SURFING        MaterialMeta_InteractionType = 1
	MaterialMeta_DOWNLOAD       MaterialMeta_InteractionType = 2
)

var MaterialMeta_InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	1: "SURFING",
	2: "DOWNLOAD",
}
var MaterialMeta_InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"SURFING":        1,
	"DOWNLOAD":       2,
}

func (x MaterialMeta_InteractionType) Enum() *MaterialMeta_InteractionType {
	p := new(MaterialMeta_InteractionType)
	*p = x
	return p
}
func (x MaterialMeta_InteractionType) String() string {
	return proto.EnumName(MaterialMeta_InteractionType_name, int32(x))
}
func (x *MaterialMeta_InteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_InteractionType_value, data, "MaterialMeta_InteractionType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_InteractionType(value)
	return nil
}
func (MaterialMeta_InteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 1}
}

// 版本号信息
type Version struct {
	Major            *uint32 `protobuf:"varint,1,opt,name=major,def=0" json:"major,omitempty"`
	Minor            *uint32 `protobuf:"varint,2,opt,name=minor,def=0" json:"minor,omitempty"`
	Micro            *uint32 `protobuf:"varint,3,opt,name=micro,def=0" json:"micro,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Version_Major uint32 = 0
const Default_Version_Minor uint32 = 0
const Default_Version_Micro uint32 = 0

func (m *Version) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return Default_Version_Major
}

func (m *Version) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return Default_Version_Minor
}

func (m *Version) GetMicro() uint32 {
	if m != nil && m.Micro != nil {
		return *m.Micro
	}
	return Default_Version_Micro
}

// 应用信息
type App struct {
	AppId            *string  `protobuf:"bytes,1,opt,name=app_id,def=" json:"app_id,omitempty"`
	ChannelId        *string  `protobuf:"bytes,2,opt,name=channel_id" json:"channel_id,omitempty"`
	AppVersion       *Version `protobuf:"bytes,3,opt,name=app_version" json:"app_version,omitempty"`
	AppPackage       *string  `protobuf:"bytes,4,opt,name=app_package" json:"app_package,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *App) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *App) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *App) GetAppVersion() *Version {
	if m != nil {
		return m.AppVersion
	}
	return nil
}

func (m *App) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

// 唯一用户标识，必需使用明文，必需按要求填写，具体填写指导详见接口说明文档
type UdId struct {
	Idfa             *string `protobuf:"bytes,1,opt,name=idfa,def=" json:"idfa,omitempty"`
	Imei             *string `protobuf:"bytes,2,opt,name=imei,def=" json:"imei,omitempty"`
	Mac              *string `protobuf:"bytes,3,opt,name=mac,def=" json:"mac,omitempty"`
	ImeiMd5          *string `protobuf:"bytes,4,opt,name=imei_md5,def=" json:"imei_md5,omitempty"`
	AndroidId        *string `protobuf:"bytes,5,opt,name=android_id,def=" json:"android_id,omitempty"`
	Baiduid          *string `protobuf:"bytes,6,opt,name=baiduid,def=" json:"baiduid,omitempty"`
	Cuid             *string `protobuf:"bytes,7,opt,name=cuid,def=" json:"cuid,omitempty"`
	IdfaMd5          *string `protobuf:"bytes,8,opt,name=idfa_md5,def=" json:"idfa_md5,omitempty"`
	AndroididMd5     *string `protobuf:"bytes,9,opt,name=androidid_md5,def=" json:"androidid_md5,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UdId) Reset()                    { *m = UdId{} }
func (m *UdId) String() string            { return proto.CompactTextString(m) }
func (*UdId) ProtoMessage()               {}
func (*UdId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UdId) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *UdId) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *UdId) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *UdId) GetImeiMd5() string {
	if m != nil && m.ImeiMd5 != nil {
		return *m.ImeiMd5
	}
	return ""
}

func (m *UdId) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

func (m *UdId) GetBaiduid() string {
	if m != nil && m.Baiduid != nil {
		return *m.Baiduid
	}
	return ""
}

func (m *UdId) GetCuid() string {
	if m != nil && m.Cuid != nil {
		return *m.Cuid
	}
	return ""
}

func (m *UdId) GetIdfaMd5() string {
	if m != nil && m.IdfaMd5 != nil {
		return *m.IdfaMd5
	}
	return ""
}

func (m *UdId) GetAndroididMd5() string {
	if m != nil && m.AndroididMd5 != nil {
		return *m.AndroididMd5
	}
	return ""
}

// 二维尺寸信息
type Size struct {
	Width            *uint32 `protobuf:"varint,1,opt,name=width,def=0" json:"width,omitempty"`
	Height           *uint32 `protobuf:"varint,2,opt,name=height,def=0" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Size) Reset()                    { *m = Size{} }
func (m *Size) String() string            { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()               {}
func (*Size) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_Size_Width uint32 = 0
const Default_Size_Height uint32 = 0

func (m *Size) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return Default_Size_Width
}

func (m *Size) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return Default_Size_Height
}

// 设备信息
type Device struct {
	DeviceType       *Device_DeviceType `protobuf:"varint,1,opt,name=device_type,enum=mobads.apiv5.Device_DeviceType" json:"device_type,omitempty"`
	OsType           *Device_OsType     `protobuf:"varint,2,opt,name=os_type,enum=mobads.apiv5.Device_OsType" json:"os_type,omitempty"`
	OsVersion        *Version           `protobuf:"bytes,3,opt,name=os_version" json:"os_version,omitempty"`
	Vendor           []byte             `protobuf:"bytes,4,opt,name=vendor,def=" json:"vendor,omitempty"`
	Model            []byte             `protobuf:"bytes,5,opt,name=model,def=" json:"model,omitempty"`
	Udid             *UdId              `protobuf:"bytes,6,opt,name=udid" json:"udid,omitempty"`
	ScreenSize       *Size              `protobuf:"bytes,7,opt,name=screen_size" json:"screen_size,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Device) GetDeviceType() Device_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Device_PHONE
}

func (m *Device) GetOsType() Device_OsType {
	if m != nil && m.OsType != nil {
		return *m.OsType
	}
	return Device_ANDROID
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() []byte {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *Device) GetModel() []byte {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *Device) GetUdid() *UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

// WiFi热点信息
type WiFiAp struct {
	ApMac            *string `protobuf:"bytes,1,opt,name=ap_mac" json:"ap_mac,omitempty"`
	Rssi             *int32  `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	ApName           []byte  `protobuf:"bytes,3,opt,name=ap_name" json:"ap_name,omitempty"`
	IsConnected      *bool   `protobuf:"varint,4,opt,name=is_connected" json:"is_connected,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WiFiAp) Reset()                    { *m = WiFiAp{} }
func (m *WiFiAp) String() string            { return proto.CompactTextString(m) }
func (*WiFiAp) ProtoMessage()               {}
func (*WiFiAp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WiFiAp) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *WiFiAp) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *WiFiAp) GetApName() []byte {
	if m != nil {
		return m.ApName
	}
	return nil
}

func (m *WiFiAp) GetIsConnected() bool {
	if m != nil && m.IsConnected != nil {
		return *m.IsConnected
	}
	return false
}

// 网络环境信息
type Network struct {
	Ipv4             *string                 `protobuf:"bytes,1,opt,name=ipv4" json:"ipv4,omitempty"`
	ConnectionType   *Network_ConnectionType `protobuf:"varint,2,opt,name=connection_type,enum=mobads.apiv5.Network_ConnectionType" json:"connection_type,omitempty"`
	OperatorType     *Network_OperatorType   `protobuf:"varint,3,opt,name=operator_type,enum=mobads.apiv5.Network_OperatorType" json:"operator_type,omitempty"`
	CellularId       *string                 `protobuf:"bytes,4,opt,name=cellular_id" json:"cellular_id,omitempty"`
	WifiAps          []*WiFiAp               `protobuf:"bytes,5,rep,name=wifi_aps" json:"wifi_aps,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Network) Reset()                    { *m = Network{} }
func (m *Network) String() string            { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()               {}
func (*Network) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Network) GetIpv4() string {
	if m != nil && m.Ipv4 != nil {
		return *m.Ipv4
	}
	return ""
}

func (m *Network) GetConnectionType() Network_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return Network_CONNECTION_UNKNOWN
}

func (m *Network) GetOperatorType() Network_OperatorType {
	if m != nil && m.OperatorType != nil {
		return *m.OperatorType
	}
	return Network_UNKNOWN_OPERATOR
}

func (m *Network) GetCellularId() string {
	if m != nil && m.CellularId != nil {
		return *m.CellularId
	}
	return ""
}

func (m *Network) GetWifiAps() []*WiFiAp {
	if m != nil {
		return m.WifiAps
	}
	return nil
}

// GPS信息
type Gps struct {
	CoordinateType   *Gps_CoordinateType `protobuf:"varint,1,opt,name=coordinate_type,enum=mobads.apiv5.Gps_CoordinateType" json:"coordinate_type,omitempty"`
	Longitude        *float64            `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude         *float64            `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Timestamp        *uint32             `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Gps) Reset()                    { *m = Gps{} }
func (m *Gps) String() string            { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()               {}
func (*Gps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Gps) GetCoordinateType() Gps_CoordinateType {
	if m != nil && m.CoordinateType != nil {
		return *m.CoordinateType
	}
	return Gps_WGS84
}

func (m *Gps) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 广告效果跟踪信息
type Tracking struct {
	TrackingEvent    *Tracking_TrackingEvent `protobuf:"varint,1,opt,name=tracking_event,enum=mobads.apiv5.Tracking_TrackingEvent" json:"tracking_event,omitempty"`
	TrackingUrl      []string                `protobuf:"bytes,2,rep,name=tracking_url" json:"tracking_url,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Tracking) Reset()                    { *m = Tracking{} }
func (m *Tracking) String() string            { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()               {}
func (*Tracking) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Tracking) GetTrackingEvent() Tracking_TrackingEvent {
	if m != nil && m.TrackingEvent != nil {
		return *m.TrackingEvent
	}
	return Tracking_AD_CLICK
}

func (m *Tracking) GetTrackingUrl() []string {
	if m != nil {
		return m.TrackingUrl
	}
	return nil
}

type Video struct {
	Title            []byte           `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ContentLength    *uint32          `protobuf:"varint,2,opt,name=content_length" json:"content_length,omitempty"`
	Copyright        *Video_CopyRight `protobuf:"varint,3,opt,name=copyright,enum=mobads.apiv5.Video_CopyRight" json:"copyright,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Video) Reset()                    { *m = Video{} }
func (m *Video) String() string            { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()               {}
func (*Video) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Video) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Video) GetContentLength() uint32 {
	if m != nil && m.ContentLength != nil {
		return *m.ContentLength
	}
	return 0
}

func (m *Video) GetCopyright() Video_CopyRight {
	if m != nil && m.Copyright != nil {
		return *m.Copyright
	}
	return Video_CR_NONE
}

// 广告位信息
type AdSlot struct {
	AdslotId         *string  `protobuf:"bytes,1,opt,name=adslot_id" json:"adslot_id,omitempty"`
	AdslotSize       *Size    `protobuf:"bytes,2,opt,name=adslot_size" json:"adslot_size,omitempty"`
	Topics           [][]byte `protobuf:"bytes,3,rep,name=topics" json:"topics,omitempty"`
	Video            *Video   `protobuf:"bytes,4,opt,name=video" json:"video,omitempty"`
	Ctkey            *string  `protobuf:"bytes,5,opt,name=ctkey" json:"ctkey,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AdSlot) Reset()                    { *m = AdSlot{} }
func (m *AdSlot) String() string            { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()               {}
func (*AdSlot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AdSlot) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *AdSlot) GetAdslotSize() *Size {
	if m != nil {
		return m.AdslotSize
	}
	return nil
}

func (m *AdSlot) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *AdSlot) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *AdSlot) GetCtkey() string {
	if m != nil && m.Ctkey != nil {
		return *m.Ctkey
	}
	return ""
}

// Baidu Mobads API请求
type MobadsRequest struct {
	RequestId           *string                            `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	ApiVersion          *Version                           `protobuf:"bytes,2,opt,name=api_version" json:"api_version,omitempty"`
	App                 *App                               `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Device              *Device                            `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	Network             *Network                           `protobuf:"bytes,5,opt,name=network" json:"network,omitempty"`
	Gps                 *Gps                               `protobuf:"bytes,6,opt,name=gps" json:"gps,omitempty"`
	Adslot              *AdSlot                            `protobuf:"bytes,7,opt,name=adslot" json:"adslot,omitempty"`
	IsDebug             *bool                              `protobuf:"varint,8,opt,name=is_debug,def=0" json:"is_debug,omitempty"`
	RequestProtocolType *MobadsRequest_RequestProtocolType `protobuf:"varint,9,opt,name=request_protocol_type,enum=mobads.apiv5.MobadsRequest_RequestProtocolType,def=1" json:"request_protocol_type,omitempty"`
	XXX_unrecognized    []byte                             `json:"-"`
}

func (m *MobadsRequest) Reset()                    { *m = MobadsRequest{} }
func (m *MobadsRequest) String() string            { return proto.CompactTextString(m) }
func (*MobadsRequest) ProtoMessage()               {}
func (*MobadsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

const Default_MobadsRequest_IsDebug bool = false
const Default_MobadsRequest_RequestProtocolType MobadsRequest_RequestProtocolType = MobadsRequest_HTTP_PROTOCOL_TYPE

func (m *MobadsRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsRequest) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *MobadsRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *MobadsRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *MobadsRequest) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *MobadsRequest) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *MobadsRequest) GetAdslot() *AdSlot {
	if m != nil {
		return m.Adslot
	}
	return nil
}

func (m *MobadsRequest) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return Default_MobadsRequest_IsDebug
}

func (m *MobadsRequest) GetRequestProtocolType() MobadsRequest_RequestProtocolType {
	if m != nil && m.RequestProtocolType != nil {
		return *m.RequestProtocolType
	}
	return Default_MobadsRequest_RequestProtocolType
}

// 广告元数据组索引结构
// 一条广告可能包含多个物料元信息,我们统称这些元信息为广告元数据组
// 返回广告时，total_num表明当前广告包含的物料元数据个数，current_index表明当前的物料元数据在元数据组中的索引
// 请求多个广告返回时，ad_key唯一标识一个广告元数据组(一个广告)，MetaIndex标识一个元数据组中的每个元数据信息
type MetaIndex struct {
	TotalNum         *uint32 `protobuf:"varint,1,opt,name=total_num" json:"total_num,omitempty"`
	CurrentIndex     *uint32 `protobuf:"varint,2,opt,name=current_index" json:"current_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MetaIndex) Reset()                    { *m = MetaIndex{} }
func (m *MetaIndex) String() string            { return proto.CompactTextString(m) }
func (*MetaIndex) ProtoMessage()               {}
func (*MetaIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MetaIndex) GetTotalNum() uint32 {
	if m != nil && m.TotalNum != nil {
		return *m.TotalNum
	}
	return 0
}

func (m *MetaIndex) GetCurrentIndex() uint32 {
	if m != nil && m.CurrentIndex != nil {
		return *m.CurrentIndex
	}
	return 0
}

// 广告物料元数据信息
type MaterialMeta struct {
	CreativeType     *MaterialMeta_CreativeType    `protobuf:"varint,1,opt,name=creative_type,enum=mobads.apiv5.MaterialMeta_CreativeType" json:"creative_type,omitempty"`
	InteractionType  *MaterialMeta_InteractionType `protobuf:"varint,2,opt,name=interaction_type,enum=mobads.apiv5.MaterialMeta_InteractionType" json:"interaction_type,omitempty"`
	WinNoticeUrl     []string                      `protobuf:"bytes,3,rep,name=win_notice_url" json:"win_notice_url,omitempty"`
	ClickUrl         *string                       `protobuf:"bytes,4,opt,name=click_url" json:"click_url,omitempty"`
	Title            []byte                        `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description      [][]byte                      `protobuf:"bytes,6,rep,name=description" json:"description,omitempty"`
	IconSrc          []string                      `protobuf:"bytes,7,rep,name=icon_src" json:"icon_src,omitempty"`
	ImageSrc         []string                      `protobuf:"bytes,8,rep,name=image_src" json:"image_src,omitempty"`
	AppPackage       *string                       `protobuf:"bytes,9,opt,name=app_package" json:"app_package,omitempty"`
	AppSize          *uint32                       `protobuf:"varint,10,opt,name=app_size" json:"app_size,omitempty"`
	VideoUrl         *string                       `protobuf:"bytes,11,opt,name=video_url" json:"video_url,omitempty"`
	VideoDuration    *uint32                       `protobuf:"varint,12,opt,name=video_duration" json:"video_duration,omitempty"`
	MetaIndex        *MetaIndex                    `protobuf:"bytes,13,opt,name=meta_index" json:"meta_index,omitempty"`
	MaterialWidth    *uint32                       `protobuf:"varint,14,opt,name=material_width" json:"material_width,omitempty"`
	MaterialHeight   *uint32                       `protobuf:"varint,15,opt,name=material_height" json:"material_height,omitempty"`
	BrandName        *string                       `protobuf:"bytes,16,opt,name=brand_name" json:"brand_name,omitempty"`
	AdTitle          *string                       `protobuf:"bytes,17,opt,name=ad_title" json:"ad_title,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *MaterialMeta) Reset()                    { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()               {}
func (*MaterialMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MaterialMeta) GetCreativeType() MaterialMeta_CreativeType {
	if m != nil && m.CreativeType != nil {
		return *m.CreativeType
	}
	return MaterialMeta_NO_TYPE
}

func (m *MaterialMeta) GetInteractionType() MaterialMeta_InteractionType {
	if m != nil && m.InteractionType != nil {
		return *m.InteractionType
	}
	return MaterialMeta_NO_INTERACTION
}

func (m *MaterialMeta) GetWinNoticeUrl() []string {
	if m != nil {
		return m.WinNoticeUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() string {
	if m != nil && m.ClickUrl != nil {
		return *m.ClickUrl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *MaterialMeta) GetDescription() [][]byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *MaterialMeta) GetIconSrc() []string {
	if m != nil {
		return m.IconSrc
	}
	return nil
}

func (m *MaterialMeta) GetImageSrc() []string {
	if m != nil {
		return m.ImageSrc
	}
	return nil
}

func (m *MaterialMeta) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

func (m *MaterialMeta) GetAppSize() uint32 {
	if m != nil && m.AppSize != nil {
		return *m.AppSize
	}
	return 0
}

func (m *MaterialMeta) GetVideoUrl() string {
	if m != nil && m.VideoUrl != nil {
		return *m.VideoUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoDuration() uint32 {
	if m != nil && m.VideoDuration != nil {
		return *m.VideoDuration
	}
	return 0
}

func (m *MaterialMeta) GetMetaIndex() *MetaIndex {
	if m != nil {
		return m.MetaIndex
	}
	return nil
}

func (m *MaterialMeta) GetMaterialWidth() uint32 {
	if m != nil && m.MaterialWidth != nil {
		return *m.MaterialWidth
	}
	return 0
}

func (m *MaterialMeta) GetMaterialHeight() uint32 {
	if m != nil && m.MaterialHeight != nil {
		return *m.MaterialHeight
	}
	return 0
}

func (m *MaterialMeta) GetBrandName() string {
	if m != nil && m.BrandName != nil {
		return *m.BrandName
	}
	return ""
}

func (m *MaterialMeta) GetAdTitle() string {
	if m != nil && m.AdTitle != nil {
		return *m.AdTitle
	}
	return ""
}

// 广告信息
// 同时填充material_meta和meta_group
// 建议使用meta_group，当前为兼容方案，后续版本将合并material_meta和meta_group为meta_group
type Ad struct {
	AdslotId         *string         `protobuf:"bytes,1,opt,name=adslot_id" json:"adslot_id,omitempty"`
	HtmlSnippet      []byte          `protobuf:"bytes,2,opt,name=html_snippet" json:"html_snippet,omitempty"`
	MaterialMeta     *MaterialMeta   `protobuf:"bytes,3,opt,name=material_meta" json:"material_meta,omitempty"`
	AdKey            *string         `protobuf:"bytes,4,opt,name=ad_key" json:"ad_key,omitempty"`
	AdTracking       []*Tracking     `protobuf:"bytes,5,rep,name=ad_tracking" json:"ad_tracking,omitempty"`
	MetaGroup        []*MaterialMeta `protobuf:"bytes,6,rep,name=meta_group" json:"meta_group,omitempty"`
	MobAdtext        *string         `protobuf:"bytes,7,opt,name=mob_adtext" json:"mob_adtext,omitempty"`
	MobAdlogo        *string         `protobuf:"bytes,8,opt,name=mob_adlogo" json:"mob_adlogo,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Ad) Reset()                    { *m = Ad{} }
func (m *Ad) String() string            { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()               {}
func (*Ad) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Ad) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *Ad) GetHtmlSnippet() []byte {
	if m != nil {
		return m.HtmlSnippet
	}
	return nil
}

func (m *Ad) GetMaterialMeta() *MaterialMeta {
	if m != nil {
		return m.MaterialMeta
	}
	return nil
}

func (m *Ad) GetAdKey() string {
	if m != nil && m.AdKey != nil {
		return *m.AdKey
	}
	return ""
}

func (m *Ad) GetAdTracking() []*Tracking {
	if m != nil {
		return m.AdTracking
	}
	return nil
}

func (m *Ad) GetMetaGroup() []*MaterialMeta {
	if m != nil {
		return m.MetaGroup
	}
	return nil
}

func (m *Ad) GetMobAdtext() string {
	if m != nil && m.MobAdtext != nil {
		return *m.MobAdtext
	}
	return ""
}

func (m *Ad) GetMobAdlogo() string {
	if m != nil && m.MobAdlogo != nil {
		return *m.MobAdlogo
	}
	return ""
}

// Baidu Mobads API应答
type MobadsResponse struct {
	RequestId        *string `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	ErrorCode        *uint64 `protobuf:"varint,2,opt,name=error_code" json:"error_code,omitempty"`
	Ads              []*Ad   `protobuf:"bytes,3,rep,name=ads" json:"ads,omitempty"`
	ExpirationTime   *uint32 `protobuf:"varint,4,opt,name=expiration_time" json:"expiration_time,omitempty"`
	SearchKey        *string `protobuf:"bytes,5,opt,name=search_key" json:"search_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MobadsResponse) Reset()                    { *m = MobadsResponse{} }
func (m *MobadsResponse) String() string            { return proto.CompactTextString(m) }
func (*MobadsResponse) ProtoMessage()               {}
func (*MobadsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MobadsResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsResponse) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MobadsResponse) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *MobadsResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

func (m *MobadsResponse) GetSearchKey() string {
	if m != nil && m.SearchKey != nil {
		return *m.SearchKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "mobads.apiv5.Version")
	proto.RegisterType((*App)(nil), "mobads.apiv5.App")
	proto.RegisterType((*UdId)(nil), "mobads.apiv5.UdId")
	proto.RegisterType((*Size)(nil), "mobads.apiv5.Size")
	proto.RegisterType((*Device)(nil), "mobads.apiv5.Device")
	proto.RegisterType((*WiFiAp)(nil), "mobads.apiv5.WiFiAp")
	proto.RegisterType((*Network)(nil), "mobads.apiv5.Network")
	proto.RegisterType((*Gps)(nil), "mobads.apiv5.Gps")
	proto.RegisterType((*Tracking)(nil), "mobads.apiv5.Tracking")
	proto.RegisterType((*Video)(nil), "mobads.apiv5.Video")
	proto.RegisterType((*AdSlot)(nil), "mobads.apiv5.AdSlot")
	proto.RegisterType((*MobadsRequest)(nil), "mobads.apiv5.MobadsRequest")
	proto.RegisterType((*MetaIndex)(nil), "mobads.apiv5.MetaIndex")
	proto.RegisterType((*MaterialMeta)(nil), "mobads.apiv5.MaterialMeta")
	proto.RegisterType((*Ad)(nil), "mobads.apiv5.Ad")
	proto.RegisterType((*MobadsResponse)(nil), "mobads.apiv5.MobadsResponse")
	proto.RegisterEnum("mobads.apiv5.Device_DeviceType", Device_DeviceType_name, Device_DeviceType_value)
	proto.RegisterEnum("mobads.apiv5.Device_OsType", Device_OsType_name, Device_OsType_value)
	proto.RegisterEnum("mobads.apiv5.Network_ConnectionType", Network_ConnectionType_name, Network_ConnectionType_value)
	proto.RegisterEnum("mobads.apiv5.Network_OperatorType", Network_OperatorType_name, Network_OperatorType_value)
	proto.RegisterEnum("mobads.apiv5.Gps_CoordinateType", Gps_CoordinateType_name, Gps_CoordinateType_value)
	proto.RegisterEnum("mobads.apiv5.Tracking_TrackingEvent", Tracking_TrackingEvent_name, Tracking_TrackingEvent_value)
	proto.RegisterEnum("mobads.apiv5.Video_CopyRight", Video_CopyRight_name, Video_CopyRight_value)
	proto.RegisterEnum("mobads.apiv5.MobadsRequest_RequestProtocolType", MobadsRequest_RequestProtocolType_name, MobadsRequest_RequestProtocolType_value)
	proto.RegisterEnum("mobads.apiv5.MaterialMeta_CreativeType", MaterialMeta_CreativeType_name, MaterialMeta_CreativeType_value)
	proto.RegisterEnum("mobads.apiv5.MaterialMeta_InteractionType", MaterialMeta_InteractionType_name, MaterialMeta_InteractionType_value)
}

var fileDescriptor0 = []byte{
	// 1811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x57, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x36, 0xdf, 0x64, 0xf3, 0x21, 0x08, 0x92, 0x57, 0xde, 0x4d, 0xed, 0xae, 0x0b, 0xd9, 0xca,
	0x26, 0xeb, 0x94, 0xa2, 0x28, 0x56, 0x55, 0xd6, 0x95, 0x17, 0x4d, 0xc2, 0x34, 0x76, 0x29, 0x80,
	0x45, 0x42, 0x96, 0x73, 0x9a, 0x82, 0x80, 0x31, 0x35, 0x31, 0x08, 0x20, 0x00, 0x28, 0x5b, 0x39,
	0xa7, 0x2a, 0xaf, 0xf3, 0xde, 0xf6, 0x94, 0x63, 0x2e, 0xf9, 0x17, 0x39, 0xe4, 0x0f, 0xe4, 0x07,
	0xa4, 0x52, 0xb9, 0xe4, 0x90, 0xa4, 0x2a, 0xf7, 0xf4, 0x3c, 0x08, 0x89, 0x34, 0xd7, 0xb5, 0x27,
	0x62, 0x7a, 0x7a, 0x7a, 0x7a, 0xba, 0xbf, 0xfe, 0xba, 0x09, 0xf7, 0x2e, 0x3c, 0x16, 0x2c, 0xc9,
	0x22, 0xbe, 0xf0, 0x82, 0x8c, 0x78, 0x09, 0x23, 0x27, 0x87, 0x49, 0x1a, 0xe7, 0xb1, 0xde, 0x91,
	0xb2, 0x43, 0x94, 0x5d, 0x9d, 0x18, 0x3f, 0x85, 0xc6, 0x33, 0x9a, 0x66, 0x2c, 0x8e, 0x74, 0x0d,
	0x6a, 0x0b, 0xef, 0x17, 0x71, 0x7a, 0xaf, 0x74, 0xbf, 0xf4, 0xed, 0xee, 0xa3, 0xd2, 0x91, 0x90,
	0xb0, 0x08, 0x25, 0xe5, 0x35, 0x89, 0x9f, 0xc6, 0xf7, 0x2a, 0x4a, 0x62, 0x84, 0x50, 0xe9, 0x27,
	0x09, 0x6e, 0xd4, 0xbd, 0x24, 0x21, 0x2c, 0x10, 0xa7, 0x5b, 0x8f, 0xee, 0xe8, 0x3a, 0x80, 0x7f,
	0xe9, 0x45, 0x11, 0x0d, 0xb9, 0x94, 0x5b, 0x68, 0xe9, 0x9f, 0x40, 0x9b, 0x6b, 0x5d, 0xc9, 0x1b,
	0x85, 0x91, 0xf6, 0xf1, 0xdd, 0xc3, 0xdb, 0x1e, 0x1d, 0xae, 0xdc, 0xd9, 0x93, 0xba, 0x89, 0xe7,
	0xbf, 0xf4, 0xe6, 0xf4, 0x5e, 0x95, 0x1b, 0x30, 0xfe, 0x5c, 0x82, 0xea, 0x59, 0x60, 0x05, 0x7a,
	0x0f, 0xaa, 0x2c, 0x78, 0xe1, 0x15, 0xb7, 0xf1, 0xf5, 0x82, 0x32, 0x79, 0x0f, 0xae, 0xbb, 0x50,
	0x59, 0x78, 0xbe, 0xb8, 0x41, 0x3a, 0xd3, 0xe4, 0xdb, 0x64, 0x11, 0x9c, 0x48, 0x4b, 0x28, 0xdb,
	0x07, 0xf0, 0xa2, 0x20, 0x8d, 0x59, 0xc0, 0x1d, 0xac, 0x29, 0xe9, 0x2e, 0x34, 0x44, 0xe8, 0x50,
	0x54, 0xbf, 0xb1, 0xed, 0xf3, 0x75, 0xe3, 0x96, 0x31, 0xbc, 0x5b, 0x18, 0x6b, 0x2a, 0xd9, 0x01,
	0x74, 0x95, 0x31, 0x34, 0xc7, 0x37, 0x5a, 0x72, 0xc3, 0x78, 0x00, 0xd5, 0x19, 0xfb, 0x15, 0xe5,
	0x91, 0x7b, 0xc5, 0x82, 0xfc, 0xf2, 0x26, 0xba, 0xbb, 0x50, 0xbf, 0xa4, 0x6c, 0x7e, 0x99, 0x17,
	0xe1, 0x35, 0xfe, 0x5a, 0x86, 0xfa, 0x90, 0x5e, 0x31, 0x9f, 0xea, 0x0f, 0xa1, 0x1d, 0x88, 0x2f,
	0x92, 0x5f, 0x27, 0x54, 0x9c, 0xea, 0x1d, 0x7f, 0xb8, 0x1e, 0x2a, 0xa9, 0xaa, 0x7e, 0x5c, 0x54,
	0xd3, 0xbf, 0x0b, 0x8d, 0x38, 0x93, 0x27, 0xca, 0xe2, 0xc4, 0x37, 0xb6, 0x9e, 0x70, 0x32, 0xa1,
	0xfd, 0x1d, 0x00, 0xd4, 0xfe, 0x5a, 0xd9, 0xc0, 0xfc, 0x5e, 0xd1, 0x28, 0x40, 0x2c, 0xf0, 0xf0,
	0x75, 0xf0, 0xc5, 0x3b, 0x08, 0x85, 0x38, 0xa0, 0xa1, 0x88, 0x1c, 0x17, 0xdc, 0x87, 0xea, 0x32,
	0x50, 0x61, 0x6b, 0x1f, 0xeb, 0xeb, 0x76, 0x44, 0xd2, 0x3e, 0x86, 0x76, 0xe6, 0xa7, 0x94, 0x46,
	0x24, 0xc3, 0x90, 0x88, 0x78, 0xbe, 0xa1, 0xc8, 0x83, 0x65, 0x7c, 0x13, 0xe0, 0xd6, 0xa3, 0x5a,
	0x50, 0x9b, 0x3c, 0x75, 0x6c, 0x53, 0x2b, 0x21, 0xa6, 0xea, 0x6e, 0xff, 0xf1, 0xd8, 0x74, 0xb5,
	0xb2, 0xf1, 0x01, 0xd4, 0xd5, 0x3b, 0xda, 0xd0, 0xe8, 0xdb, 0xc3, 0xa9, 0x63, 0x0d, 0x51, 0xa5,
	0x01, 0x15, 0xcb, 0x99, 0xe1, 0xfe, 0x29, 0xd4, 0xcf, 0xd9, 0x13, 0xd6, 0x4f, 0x30, 0x81, 0x08,
	0x4e, 0xc2, 0xf1, 0x20, 0xe0, 0xa2, 0x77, 0xa0, 0x9a, 0x66, 0x99, 0x04, 0x4b, 0x0d, 0x1f, 0xd2,
	0xc0, 0xdd, 0xc8, 0x5b, 0x50, 0x11, 0x82, 0x0e, 0x02, 0xa3, 0xc3, 0x32, 0xe2, 0xc7, 0x88, 0x5d,
	0x3f, 0xa7, 0x81, 0x78, 0x71, 0xd3, 0xf8, 0x5b, 0x05, 0x1a, 0x36, 0xcd, 0x5f, 0xc5, 0xe9, 0x4b,
	0x6e, 0x80, 0x25, 0x57, 0x0f, 0x95, 0xb9, 0x1f, 0xc3, 0x8e, 0x52, 0xc6, 0x48, 0xdd, 0x0e, 0xfe,
	0x47, 0xeb, 0x4f, 0x53, 0xa7, 0x0f, 0x07, 0x85, 0xb2, 0xf0, 0xfe, 0x53, 0xe8, 0xc6, 0x09, 0x4d,
	0xbd, 0x3c, 0x4e, 0xe5, 0xe1, 0x8a, 0x38, 0x6c, 0x6c, 0x3f, 0xec, 0x28, 0x55, 0x71, 0x14, 0x6b,
	0xc4, 0xa7, 0x61, 0xb8, 0x0c, 0xbd, 0x94, 0x63, 0x58, 0x20, 0x5b, 0xff, 0x16, 0x34, 0x5f, 0xb1,
	0x17, 0x0c, 0x8b, 0x3e, 0xc3, 0xdc, 0x54, 0x30, 0xc4, 0xfb, 0xeb, 0xa6, 0x64, 0x54, 0x8c, 0x2f,
	0x4a, 0xd0, 0xdb, 0x70, 0xe5, 0x1d, 0xd0, 0x07, 0x8e, 0x6d, 0x9b, 0x03, 0xd7, 0x72, 0x6c, 0x72,
	0x66, 0x7f, 0x6e, 0x3b, 0xe7, 0xb6, 0x76, 0x07, 0xb3, 0xdf, 0x19, 0x98, 0xe3, 0x71, 0x21, 0x29,
	0xf1, 0x90, 0x0b, 0xc9, 0xf1, 0x48, 0x2b, 0x17, 0x8b, 0x1f, 0x8c, 0xb4, 0x4a, 0xb1, 0x78, 0x38,
	0xd2, 0xaa, 0xc5, 0xe2, 0x64, 0xa4, 0xd5, 0xf4, 0x26, 0x54, 0xcf, 0xad, 0x27, 0x96, 0x16, 0x60,
	0xfc, 0x9a, 0xa6, 0xfb, 0xd4, 0x9c, 0xda, 0x98, 0x48, 0x8a, 0xb5, 0xda, 0xb4, 0xcd, 0x73, 0xe2,
	0xfe, 0x7c, 0x62, 0x6a, 0xff, 0x6c, 0x18, 0x31, 0x74, 0xd6, 0x1e, 0xb9, 0x0f, 0x9a, 0xba, 0x97,
	0x38, 0x13, 0x73, 0xda, 0x77, 0x9d, 0xa9, 0x72, 0xe9, 0xa9, 0x65, 0xf7, 0xc9, 0xa9, 0xf3, 0xd8,
	0x1a, 0x73, 0x6c, 0xec, 0x42, 0x57, 0x4a, 0x5c, 0x73, 0x6c, 0x0e, 0x9c, 0x53, 0x74, 0xac, 0x50,
	0x3a, 0xb3, 0x2d, 0x2e, 0xa9, 0x60, 0xed, 0xf6, 0x1c, 0x7e, 0xf3, 0x8d, 0x29, 0xdf, 0xf8, 0x53,
	0x09, 0x2a, 0xa3, 0x24, 0xc3, 0x44, 0x60, 0x1e, 0xe3, 0x34, 0x60, 0x91, 0x97, 0xaf, 0x95, 0xdd,
	0xfd, 0xf5, 0xf8, 0xa1, 0x2e, 0xe6, 0x70, 0xa5, 0x28, 0x7c, 0xdc, 0x85, 0x56, 0x18, 0x47, 0x73,
	0x96, 0x2f, 0x03, 0x99, 0xfc, 0x12, 0xde, 0xdd, 0x0c, 0xbd, 0x5c, 0x4a, 0x2a, 0x42, 0x82, 0x4a,
	0x39, 0xb2, 0x50, 0x96, 0x7b, 0x8b, 0x44, 0xe4, 0xaa, 0x6b, 0x1c, 0xf1, 0x14, 0xac, 0x59, 0x42,
	0xb0, 0x9f, 0x8f, 0x66, 0x3f, 0x7c, 0x88, 0x0f, 0xc2, 0xcf, 0xd1, 0xe0, 0xb3, 0xa3, 0x63, 0x7c,
	0x08, 0x86, 0xee, 0xf1, 0xf0, 0xe8, 0x53, 0xad, 0x62, 0xfc, 0xa5, 0x0c, 0x4d, 0x37, 0x45, 0x52,
	0x64, 0xd1, 0x5c, 0xff, 0x11, 0xf4, 0x72, 0xf5, 0x4d, 0x28, 0xd6, 0x67, 0xae, 0x1c, 0xde, 0x00,
	0xde, 0x4a, 0xbf, 0xf8, 0x30, 0xb9, 0x2e, 0xc7, 0x79, 0x71, 0x7a, 0x99, 0x86, 0xe8, 0x77, 0x05,
	0x29, 0xf6, 0x1f, 0x25, 0xe8, 0xae, 0xeb, 0x61, 0xb6, 0xfa, 0x43, 0x32, 0x18, 0x5b, 0x83, 0xcf,
	0x35, 0x5e, 0xf7, 0x6d, 0x5c, 0x99, 0xcf, 0x27, 0xce, 0xec, 0x6c, 0xca, 0xe3, 0xbe, 0xda, 0x76,
	0x66, 0x26, 0x7a, 0xba, 0x0f, 0xbd, 0x67, 0xd6, 0xd0, 0x74, 0x08, 0xca, 0x66, 0x6e, 0x7f, 0xea,
	0x6a, 0xbf, 0xfd, 0xa2, 0xae, 0xbf, 0x07, 0xfb, 0x85, 0xf4, 0xc9, 0x19, 0x02, 0x62, 0x36, 0x98,
	0x9a, 0xa6, 0xad, 0xfd, 0x0e, 0xf7, 0x74, 0xe8, 0x14, 0x7b, 0xa6, 0x3d, 0xd4, 0x7e, 0x8f, 0xb2,
	0x0f, 0xe1, 0xdd, 0x75, 0x2b, 0x64, 0xd0, 0x9f, 0xae, 0x7c, 0xf8, 0x03, 0x2a, 0xdc, 0x85, 0x9d,
	0xfe, 0x64, 0xc2, 0xb7, 0x87, 0x08, 0x8c, 0xb1, 0xd3, 0x1f, 0x6a, 0xff, 0xfe, 0xb2, 0xce, 0x6f,
	0x57, 0x62, 0xcb, 0xc6, 0x73, 0xe3, 0xb1, 0xf6, 0x1f, 0x94, 0xee, 0x41, 0x57, 0x49, 0xfb, 0x88,
	0xec, 0x67, 0xa6, 0xf6, 0xdf, 0x2f, 0xeb, 0xc6, 0x1f, 0x4b, 0x50, 0x7b, 0xc6, 0x02, 0x1a, 0x23,
	0xfe, 0x6a, 0x98, 0xa7, 0x50, 0x66, 0xbb, 0x83, 0x45, 0xd0, 0xc3, 0x72, 0xce, 0xf1, 0xe5, 0x24,
	0xa4, 0xd1, 0x1c, 0x29, 0x5b, 0xf0, 0xb3, 0x7e, 0x04, 0x2d, 0x3f, 0x4e, 0xae, 0x53, 0x41, 0xd9,
	0xb2, 0x46, 0xdf, 0xdf, 0x20, 0x4b, 0x6e, 0x0e, 0xa1, 0x91, 0x5c, 0x4f, 0xb9, 0x92, 0xf1, 0x33,
	0x68, 0x15, 0x0b, 0x51, 0x0a, 0x53, 0x62, 0x73, 0x1e, 0xbb, 0xc3, 0x63, 0x86, 0x0b, 0xf3, 0xb9,
	0x35, 0x73, 0x25, 0xab, 0xe1, 0xea, 0x6c, 0x34, 0xc0, 0xf8, 0xc9, 0x1d, 0x81, 0x51, 0xcc, 0xf6,
	0x6f, 0x4a, 0x50, 0xef, 0x07, 0xb3, 0x30, 0xce, 0x39, 0x7a, 0xf0, 0x26, 0xfc, 0x2a, 0x9a, 0x2c,
	0xe7, 0x53, 0x25, 0x12, 0x7c, 0x5a, 0xfe, 0x2a, 0x3e, 0xe5, 0x04, 0x98, 0xc7, 0x09, 0xf3, 0x33,
	0xf4, 0xbb, 0x82, 0x4f, 0x34, 0xa0, 0x76, 0xc5, 0x7d, 0x15, 0x28, 0x6c, 0x1f, 0xef, 0x6d, 0x79,
	0x06, 0x8f, 0x8a, 0x9f, 0xbf, 0xa4, 0xd7, 0xb2, 0x33, 0x1a, 0x7f, 0xaf, 0x40, 0xf7, 0x54, 0x68,
	0x4d, 0xe9, 0x2f, 0x97, 0x08, 0x62, 0xde, 0xe0, 0x53, 0xf9, 0x79, 0xe3, 0x91, 0x68, 0xf0, 0xac,
	0x68, 0x29, 0xe5, 0xb7, 0xb5, 0x94, 0x0f, 0xa0, 0x82, 0x0d, 0x5e, 0xb5, 0x9d, 0xdd, 0x75, 0x1d,
	0x3e, 0x52, 0x7c, 0x04, 0x75, 0xd9, 0x01, 0x95, 0x97, 0xfb, 0xdb, 0x5a, 0x19, 0xb2, 0x5d, 0x23,
	0x92, 0xd4, 0x28, 0x1c, 0x7d, 0xe3, 0xb6, 0x15, 0x65, 0xe3, 0x6d, 0x73, 0x24, 0xc4, 0xfa, 0xb6,
	0xdb, 0x78, 0xf1, 0xe3, 0x6d, 0x32, 0x96, 0xaa, 0x2d, 0x6d, 0xdc, 0xa6, 0x92, 0x70, 0x80, 0xad,
	0x3f, 0x23, 0x01, 0xbd, 0x58, 0xce, 0x45, 0xeb, 0x6f, 0x3e, 0xaa, 0xbd, 0xf0, 0xc2, 0x8c, 0xea,
	0x17, 0x70, 0x77, 0x15, 0x0c, 0x31, 0x66, 0xf9, 0x71, 0x28, 0x19, 0xa4, 0x25, 0x80, 0xf2, 0xbd,
	0x75, 0x6b, 0x6b, 0x81, 0x3c, 0x54, 0xbf, 0x13, 0x75, 0x8e, 0xd3, 0xc0, 0x23, 0xfd, 0xa9, 0xeb,
	0x4e, 0xc8, 0x64, 0xea, 0xb8, 0xce, 0xc0, 0x19, 0x0b, 0x6e, 0x34, 0x3c, 0xd8, 0xdb, 0xa2, 0xaa,
	0xbf, 0x0b, 0x77, 0x57, 0xfc, 0xb8, 0xa6, 0x8f, 0x30, 0x43, 0x3e, 0x7f, 0xd3, 0x0e, 0x02, 0xee,
	0x00, 0xf6, 0xb8, 0x7c, 0xb6, 0xb1, 0x51, 0x36, 0x4e, 0xa0, 0x75, 0x4a, 0x73, 0xcf, 0x8a, 0x02,
	0xfa, 0x5a, 0xf0, 0x55, 0x9c, 0x7b, 0x21, 0x89, 0x96, 0x0b, 0x39, 0xb6, 0x60, 0xd9, 0x75, 0xfd,
	0x65, 0x9a, 0xf2, 0xda, 0x60, 0x5c, 0x47, 0x96, 0x86, 0xf1, 0xaf, 0x2a, 0x74, 0x4e, 0x91, 0xc1,
	0x52, 0xe6, 0x85, 0xfc, 0xbc, 0xfe, 0x13, 0xd4, 0x4b, 0x29, 0xd2, 0xdf, 0xd5, 0x1a, 0x91, 0x7e,
	0xbc, 0x11, 0x86, 0x5b, 0x47, 0x0e, 0x07, 0x4a, 0x5f, 0xbc, 0x69, 0x08, 0x1a, 0xc3, 0x12, 0x44,
	0x1a, 0xda, 0xec, 0xa9, 0x9f, 0xbc, 0xc5, 0x84, 0x75, 0x73, 0x44, 0xb5, 0xb3, 0xde, 0x2b, 0x16,
	0x91, 0x28, 0xce, 0xf9, 0x1c, 0xc5, 0x29, 0x8e, 0xc3, 0xbf, 0xc5, 0x1f, 0xe6, 0x87, 0xcc, 0x7f,
	0x29, 0x44, 0xb2, 0x69, 0x16, 0x1c, 0x20, 0xa6, 0x19, 0xde, 0x58, 0x03, 0x8a, 0xb3, 0x0a, 0x4b,
	0xb8, 0x31, 0x44, 0x0d, 0xaf, 0x1a, 0x64, 0x74, 0x86, 0xcc, 0x40, 0xb2, 0xd4, 0x47, 0x90, 0x28,
	0x43, 0x6c, 0x81, 0xd3, 0xa9, 0x10, 0x35, 0x85, 0x68, 0x63, 0x6c, 0x15, 0x63, 0x20, 0x3f, 0xc9,
	0x85, 0xa2, 0x4a, 0x41, 0x04, 0x12, 0x4f, 0x8a, 0x0a, 0x14, 0x2e, 0xb4, 0x85, 0x12, 0x7a, 0x2b,
	0x45, 0xc1, 0x12, 0x9b, 0x1f, 0xbf, 0xb6, 0x23, 0x54, 0x1f, 0x00, 0x2c, 0xf0, 0x75, 0x2a, 0xe0,
	0x5d, 0x81, 0xce, 0x83, 0x8d, 0x28, 0x14, 0x39, 0x43, 0x23, 0x0b, 0x15, 0x12, 0x22, 0xe7, 0xcd,
	0x9e, 0x30, 0x72, 0x00, 0x3b, 0x85, 0x5c, 0x4d, 0x9d, 0x3b, 0x62, 0x03, 0xab, 0xf8, 0x22, 0xc5,
	0xd1, 0x55, 0x0e, 0x40, 0x5a, 0xe1, 0x6e, 0x40, 0x64, 0x3c, 0x76, 0x45, 0xf5, 0x7f, 0x86, 0x8d,
	0xf4, 0x76, 0x7e, 0x90, 0xcc, 0x6c, 0x67, 0x85, 0x32, 0x6c, 0x4e, 0xae, 0xf9, 0xdc, 0x95, 0x1d,
	0xcb, 0x3a, 0xed, 0x8f, 0x78, 0x1f, 0xe8, 0x42, 0x8b, 0x0b, 0x09, 0xf6, 0x5d, 0x1b, 0xfb, 0x2e,
	0xee, 0x08, 0x42, 0xd7, 0xaa, 0xc8, 0x8a, 0x3b, 0x9b, 0x89, 0xc2, 0xae, 0x8c, 0xe6, 0x2c, 0xdb,
	0xc5, 0x9e, 0x2c, 0x66, 0x0f, 0xb4, 0x8a, 0x57, 0x60, 0x83, 0x79, 0x62, 0xd9, 0x23, 0xd9, 0x63,
	0x0a, 0x9e, 0x2f, 0x1b, 0xff, 0x2b, 0x41, 0xb9, 0x1f, 0x6c, 0x63, 0x44, 0x6c, 0x69, 0x97, 0xf9,
	0x22, 0x24, 0x59, 0xc4, 0x92, 0x84, 0xca, 0xc9, 0xba, 0xa3, 0x7f, 0x1f, 0xba, 0xc5, 0xe3, 0x79,
	0x28, 0x15, 0xe7, 0xbc, 0xf7, 0xd5, 0x50, 0x12, 0x23, 0x63, 0x40, 0x38, 0xfd, 0x49, 0x7c, 0x3c,
	0xe0, 0x54, 0x4b, 0x56, 0xed, 0x52, 0xcd, 0x55, 0xef, 0x6c, 0x6f, 0xb3, 0xfa, 0xa1, 0xca, 0xd8,
	0x3c, 0x8d, 0x97, 0x89, 0x00, 0xcf, 0xdb, 0x2f, 0xc3, 0x1c, 0xe0, 0x26, 0xf1, 0x82, 0x9c, 0xbe,
	0x96, 0xfc, 0xd3, 0xba, 0x91, 0x85, 0xf1, 0x3c, 0x96, 0x7f, 0x33, 0x8c, 0x5f, 0xe3, 0xc4, 0xb6,
	0xa2, 0x8e, 0x2c, 0x89, 0xa3, 0x8c, 0x6e, 0x25, 0x61, 0x94, 0xd1, 0x34, 0xc5, 0x69, 0xd2, 0x8f,
	0xd5, 0x34, 0x52, 0xd5, 0xdf, 0x47, 0xb2, 0x0d, 0x24, 0xfd, 0xb7, 0x8f, 0xb5, 0x4d, 0x6e, 0xe3,
	0xf0, 0xa0, 0xaf, 0x13, 0x26, 0x71, 0x47, 0xf8, 0x94, 0x22, 0x07, 0x14, 0x6e, 0x2b, 0xa3, 0x5e,
	0xea, 0x5f, 0x92, 0xa2, 0x15, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x9b, 0xba, 0x9a, 0x5c,
	0x0e, 0x00, 0x00,
}
